/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graph;

import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import taxi.DAO.TaxiDAO;
import taxi.DAO.LocationDAO;
import taxi.metier.API_LOCATIONTAXI;
import taxi.metier.API_TAXI;

/**
 *
 * @author Allison
 */
public class Affich_loc extends javax.swing.JPanel {

    TaxiDAO taxiDAO = null;
    API_TAXI t1 = null;
    LocationDAO locationDAO = null;
    DefaultTableModel dft1 = new DefaultTableModel();

    /**
     * Creates new form Affich_loc
     */
    public Affich_loc() {
        initComponents();

        dft1.addColumn("Id loc");
        dft1.addColumn("Date location");
        dft1.addColumn("Km totaux");
        dft1.addColumn("Acompte");
        dft1.addColumn("Total");
        dft1.addColumn("Adresse début");
        dft1.addColumn("Adresse fin");
        dft1.addColumn("Id client");
        dft1.addColumn("Id taxi");
        tbl_rech.setModel(dft1);

    }

    public void setTaxiDAO(TaxiDAO taxiDAO) {
        this.taxiDAO = taxiDAO;
    }

    public void setLocationDAO(LocationDAO locationDAO) {
        this.locationDAO = locationDAO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_rech = new javax.swing.JTable();
        txt_imma = new javax.swing.JTextField();
        lbl_imma = new javax.swing.JLabel();

        lbl_titre.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        lbl_titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titre.setText("Affichage des locations d'un taxi");

        tbl_rech.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_rech);

        txt_imma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_imma.setMinimumSize(new java.awt.Dimension(50, 20));
        txt_imma.setPreferredSize(new java.awt.Dimension(150, 30));
        txt_imma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_immaActionPerformed(evt);
            }
        });

        lbl_imma.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_imma.setText("Immatriculation recherchée :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_imma)
                .addGap(18, 18, 18)
                .addComponent(txt_imma, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_imma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_imma))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_immaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_immaActionPerformed
        try {
            if (!txt_imma.getText().isEmpty()) {
                String imma = txt_imma.getText();
                t1 = taxiDAO.rechImma(imma);
                //0-4 year   5-7 month   9-10 day

                int id = t1.getIdtaxi();

                List<API_LOCATIONTAXI> loc = locationDAO.rechTaxi(id);
                int nr = dft1.getRowCount();
                for (int i = nr - 1; i >= 0; i--) {
                    dft1.removeRow(i);
                }
                
                for (API_LOCATIONTAXI vec : loc) {
                    Vector v = new Vector();
          
                    v.add(vec.getIdloc());
                    v.add(vec.getDateloc());
                    v.add(vec.getKmtotal());
                    v.add(vec.getAcompte());
                    v.add(vec.getTotal());
                    v.add(vec.getAdrdebut());
                    v.add(vec.getAdrfin());
                    v.add(vec.getIdclient());
                    v.add(vec.getIdtaxi());

                    dft1.addRow(v);

                }

            } else {
                JOptionPane.showMessageDialog(this, "L'immatriculation est vide, veuillez le remplir!", "ERREUR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txt_immaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_imma;
    private javax.swing.JLabel lbl_titre;
    private javax.swing.JTable tbl_rech;
    private javax.swing.JTextField txt_imma;
    // End of variables declaration//GEN-END:variables
}
