/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graph;

import java.awt.CardLayout;
import java.sql.Connection;
import javax.swing.JOptionPane;
import myconnections.DBConnection;
import taxi.DAO.TaxiDAO;

/**
 *
 * @author Allison
 */
public class Gestion_main extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_main
     */
    CardLayout cardl;
    
    public Gestion_main() {
        initComponents();
        cardl=(CardLayout)this.getContentPane().getLayout();
        cardl.show(this.getContentPane(), "card2");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background2 = new graph.Background();
        crea_taxi1 = new graph.Crea_taxi();
        modif_taxi1 = new graph.Modif_taxi();
        suppr_taxi1 = new graph.Suppr_taxi();
        recherche_taxi_id1 = new graph.Recherche_taxi_id();
        recherche_taxi_descri1 = new graph.Recherche_taxi_descri();
        jMenuBar2 = new javax.swing.JMenuBar();
        main_taxi = new javax.swing.JMenu();
        create_taxi = new javax.swing.JMenuItem();
        update_taxi = new javax.swing.JMenuItem();
        read_main = new javax.swing.JMenu();
        read_id = new javax.swing.JMenuItem();
        read_descri = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout background2Layout = new javax.swing.GroupLayout(background2);
        background2.setLayout(background2Layout);
        background2Layout.setHorizontalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        background2Layout.setVerticalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(background2, "card2");

        javax.swing.GroupLayout crea_taxi1Layout = new javax.swing.GroupLayout(crea_taxi1);
        crea_taxi1.setLayout(crea_taxi1Layout);
        crea_taxi1Layout.setHorizontalGroup(
            crea_taxi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        crea_taxi1Layout.setVerticalGroup(
            crea_taxi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(crea_taxi1, "card5");

        javax.swing.GroupLayout modif_taxi1Layout = new javax.swing.GroupLayout(modif_taxi1);
        modif_taxi1.setLayout(modif_taxi1Layout);
        modif_taxi1Layout.setHorizontalGroup(
            modif_taxi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        modif_taxi1Layout.setVerticalGroup(
            modif_taxi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(modif_taxi1, "card6");

        javax.swing.GroupLayout suppr_taxi1Layout = new javax.swing.GroupLayout(suppr_taxi1);
        suppr_taxi1.setLayout(suppr_taxi1Layout);
        suppr_taxi1Layout.setHorizontalGroup(
            suppr_taxi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        suppr_taxi1Layout.setVerticalGroup(
            suppr_taxi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(suppr_taxi1, "card3");

        javax.swing.GroupLayout recherche_taxi_id1Layout = new javax.swing.GroupLayout(recherche_taxi_id1);
        recherche_taxi_id1.setLayout(recherche_taxi_id1Layout);
        recherche_taxi_id1Layout.setHorizontalGroup(
            recherche_taxi_id1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        recherche_taxi_id1Layout.setVerticalGroup(
            recherche_taxi_id1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(recherche_taxi_id1, "card4");

        javax.swing.GroupLayout recherche_taxi_descri1Layout = new javax.swing.GroupLayout(recherche_taxi_descri1);
        recherche_taxi_descri1.setLayout(recherche_taxi_descri1Layout);
        recherche_taxi_descri1Layout.setHorizontalGroup(
            recherche_taxi_descri1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        recherche_taxi_descri1Layout.setVerticalGroup(
            recherche_taxi_descri1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(recherche_taxi_descri1, "card7");

        main_taxi.setText("Taxi");

        create_taxi.setText("Ajouter");
        main_taxi.add(create_taxi);

        update_taxi.setText("Modifier");
        main_taxi.add(update_taxi);

        read_main.setText("Rechercher");

        read_id.setText("sur l'id");
        read_main.add(read_id);

        read_descri.setText("sur la description");
        read_main.add(read_descri);

        main_taxi.add(read_main);

        jMenuBar2.add(main_taxi);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private graph.Background background2;
    private graph.Crea_taxi crea_taxi1;
    private javax.swing.JMenuItem create_taxi;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu main_taxi;
    private graph.Modif_taxi modif_taxi1;
    private javax.swing.JMenuItem read_descri;
    private javax.swing.JMenuItem read_id;
    private javax.swing.JMenu read_main;
    private graph.Recherche_taxi_descri recherche_taxi_descri1;
    private graph.Recherche_taxi_id recherche_taxi_id1;
    private graph.Suppr_taxi suppr_taxi1;
    private javax.swing.JMenuItem update_taxi;
    // End of variables declaration//GEN-END:variables
}
