/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graph;

import java.awt.CardLayout;
import java.sql.Connection;
import javax.swing.JOptionPane;
import myconnections.DBConnection;
import taxi.DAO.TaxiDAO;

/**
 *
 * @author Allison
 */
public class Gestion_main extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_main
     */
    CardLayout cardl;

    
    public Gestion_main() {
        initComponents();
        cardl=(CardLayout)this.getContentPane().getLayout();
        cardl.show(this.getContentPane(), "card2");
        
        Connection dbConnect = DBConnection.getConnection();
        if (dbConnect == null) {
            System.out.println("connection invalide");
            JOptionPane.showMessageDialog(this,"connexion invalide","ERREUR",JOptionPane.ERROR_MESSAGE);
        }
        
        TaxiDAO taxiDAO = new TaxiDAO();
        taxiDAO.setConnection(dbConnect);
        crea_taxi2.setTaxiDAO(taxiDAO);
        recherche_taxi_descri2.setTaxiDAO(taxiDAO);
        recherche_taxi_id2.setTaxiDAO(taxiDAO);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background2 = new graph.Background();
        recherche_taxi_descri2 = new graph.Recherche_taxi_descri();
        crea_taxi2 = new graph.Crea_taxi();
        recherche_taxi_id2 = new graph.Recherche_taxi_id();
        jMenuBar2 = new javax.swing.JMenuBar();
        main_taxi = new javax.swing.JMenu();
        create_taxi = new javax.swing.JMenuItem();
        update_taxi = new javax.swing.JMenuItem();
        rech_desc_taxi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout background2Layout = new javax.swing.GroupLayout(background2);
        background2.setLayout(background2Layout);
        background2Layout.setHorizontalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        background2Layout.setVerticalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        getContentPane().add(background2, "card2");
        getContentPane().add(recherche_taxi_descri2, "cardRechDesc");
        getContentPane().add(crea_taxi2, "cardCreate");
        getContentPane().add(recherche_taxi_id2, "cardGestion");

        main_taxi.setText("Taxi");

        create_taxi.setText("Ajout");
        create_taxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_taxiActionPerformed(evt);
            }
        });
        main_taxi.add(create_taxi);

        update_taxi.setText("Gestion");
        update_taxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_taxiActionPerformed(evt);
            }
        });
        main_taxi.add(update_taxi);

        rech_desc_taxi.setText("Recherche description");
        rech_desc_taxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rech_desc_taxiActionPerformed(evt);
            }
        });
        main_taxi.add(rech_desc_taxi);

        jMenuBar2.add(main_taxi);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void create_taxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_taxiActionPerformed
        setTitle("Création taxi");
        cardl.show(this.getContentPane(), "cardCreate");
    }//GEN-LAST:event_create_taxiActionPerformed

    private void update_taxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_taxiActionPerformed
        setTitle("Gestion taxi");
        cardl.show(this.getContentPane(), "cardGestion");
    }//GEN-LAST:event_update_taxiActionPerformed

    private void rech_desc_taxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rech_desc_taxiActionPerformed
        setTitle("Recherche taxi sur la description");
        cardl.show(this.getContentPane(), "cardRechDesc");
    }//GEN-LAST:event_rech_desc_taxiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private graph.Background background2;
    private graph.Crea_taxi crea_taxi2;
    private javax.swing.JMenuItem create_taxi;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu main_taxi;
    private javax.swing.JMenuItem rech_desc_taxi;
    private graph.Recherche_taxi_descri recherche_taxi_descri2;
    private graph.Recherche_taxi_id recherche_taxi_id2;
    private javax.swing.JMenuItem update_taxi;
    // End of variables declaration//GEN-END:variables
}
